### ISSUE TITLE
Clarity of functionality

### ISSUE THREAD

**Issue by teraspora** [Eventyret/Padawan#36]
The meaning of the sentence "This tool will scaffold out the following milestones" is not at all clear to me.   What does "Scaffold out" mean?   Some more detail here would be great!

**Comment by Eventyret** [comment]
Will give a bit more context out for this, thank you @teraspora 
Linking this to https://github.com/Eventyret/Padawan/issues/13 as it will be part of the Final Readme

**Comment by Eventyret** [comment]
Linking this to https://github.com/Eventyret/Padawan/issues/13 as it will be part of the Final Readme

**Comment by Eventyret** [comment]
@teraspora This better description?

**Comment by teraspora** [comment]
Yes.
