### ISSUE TITLE
Template for MS4 is missing

### ISSUE THREAD

**Issue by mrailton** [Eventyret/Padawan#55]
## Bug Report

**Current Behavior**
There is no template for Full Stack Frameworks project creation, ./templates does not contain a 'FSF' dir (or any other dir that would make sense for this).

### Environment

Not environment related

### Possible Solution

Need to create a template dir for MS4

**Comment by Eventyret** [comment]
Closing this as it was fixed https://github.com/Eventyret/Padawan/commit/ece4fe29aabcf5cb2d1bbc6c9c2b19f5128b7f6f and merged to master
